### ISSUE TITLE
Do you need an administrator role?

### ISSUE THREAD

**Issue by Charles-Hoot** [sudheera96/Group-4--Hunt-game#2]
If so, what are the responsibilities of the admin.

**Comment by Saikrishna1545** [comment]
1. yes, we need to have the administrator role. because administrator plays important role in our project , he is the one who can give access to users depends upon the role. since the different users while have the different access  when they login.
2. And Installing and configuring updated software can move to production  done by this role.
3. Monitoring system performance and troubleshooting issues. Ensuring security and efficiency of IT infrastructure can also monitored by this role.
